
export const PATH = {
    BORROWER_PATH: '/borrowservice',
    LENDDETAIL_PATH: '/lendingdetail',
    LENDSERVICE_PATH: '/service',
    LENDDING_PATH: '/lending',
    BORROWLIMIT_PATH: '/borrowlimit',
    BORROW_PATH: '/borrow',
    BORROWCREATE_PATH: '/borrowcreate',
    BORROWDETAIL_PATH: '/borrowdetail',
    LENDINGCONTRACT_PATH: '/lendingcontract',
    ACCOUNT_PATH: '/account',
    ACCOUNTPROFILE_PATH: '/profile',
    PROFILEDETAIL_PATH: '/profiledetail',
    PROFILEIDCARD_PATH: '/profileidcard',
    PROFILEBANKACCOUNT_PATH: '/profilefacebook',
    DEPOSIT_PATH: '/transaction/deposit',
    WITHDRAW_PATH: '/transaction/withdraw',
    ACCOUNTHISTORY_PATH: '/history',
    LENDLIMIT_PATH: '/lendlimit',
    PAYMENTRETURN_PATH: '/payment/return',
    HISTORYDETAIL_PATH: '/history/detail',
}